# SWD5: Scientific Python notebook 

In [1]:
# python basic collections 

a_tuple = (1, 10)

a_list = [1, 2, "3"]

a_dict = {"foo": 100, "bar": 10}

In [2]:
# tuples and list support positional indexing

a_tuple[0]

1

In [3]:
a_list[2]

'3'

In [4]:
# dictionaries don't support postional indexing

a_dict[0]

KeyError: ignored

In [5]:
a_dict["foo"]

100

## NumPy 

In [6]:
import numpy as np 

In [7]:
arr = np.arange(1000)

In [8]:
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [9]:
lst = list(range(1000))

In [10]:
lst

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [11]:
lst ** 2

TypeError: ignored

In [12]:
# list comprehension 

%timeit [i ** 2 for i in lst]

286 µs ± 5.13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
[i ** 2 for i in lst]

In [ ]:
arr ** 2

In [15]:
%timeit arr ** 2

2 µs ± 893 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
# first item in array
arr[0]

0

In [17]:
# get a range of values
arr[5:10]

array([5, 6, 7, 8, 9])

In [20]:
arr[-10:-1]

array([990, 991, 992, 993, 994, 995, 996, 997, 998])

In [21]:
# lists are homogenous in their composition
# they can contain multiple types

lst = [1, 2, 3]

lst[2] = "three"

lst

[1, 2, 'three']

In [22]:
# numpy arrays can only contain one type of data

arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr[0] = "add a string"

ValueError: ignored

In [25]:
arr[0] = 1.23

In [26]:
arr[:10]

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# numpy includes functions for creating arrays
# with placeholder values

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [29]:
np.ones(5, float)

array([1., 1., 1., 1., 1.])

In [30]:
a = np.empty(5)

a

array([1., 1., 1., 1., 1.])

In [31]:
# fill an existing array with a value

a.fill(5.5)

In [32]:
print(a)

[5.5 5.5 5.5 5.5 5.5]


In [33]:
# a range to create an array filed with a range of integers

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.linspace(0, 1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# create a range of floats over log sapce

np.logspace(1, 4, num=4)

array([   10.,   100.,  1000., 10000.])

In [36]:
?np.logspace

In [37]:
# getting random values with numpy

np.random.randn(5)

array([-0.12827569,  0.18451467,  0.8793678 ,  1.56163804,  0.90494992])

In [38]:
?np.random.randn

In [39]:
# sample from our own distribution

norm10 = np.random.normal(loc=9, scale=3, size=10)

In [40]:
norm10

array([ 6.79764312,  6.84012133, 10.98205535, 11.82787334,  6.52393271,
       12.70128254,  8.29066393, 14.33980762,  2.66875071,  9.7470593 ])

In [41]:
help(np.random.exponential)

Help on built-in function exponential:

exponential(...) method of numpy.random.mtrand.RandomState instance
    exponential(scale=1.0, size=None)
    
    Draw samples from an exponential distribution.
    
    Its probability density function is
    
    .. math:: f(x; \frac{1}{\beta}) = \frac{1}{\beta} \exp(-\frac{x}{\beta}),
    
    for ``x > 0`` and 0 elsewhere. :math:`\beta` is the scale parameter,
    which is the inverse of the rate parameter :math:`\lambda = 1/\beta`.
    The rate parameter is an alternative, widely used parameterization
    of the exponential distribution [3]_.
    
    The exponential distribution is a continuous analogue of the
    geometric distribution.  It describes many common situations, such as
    the size of raindrops measured over many rainstorms [1]_, or the time
    between page requests to Wikipedia [2]_.
    
    .. note::
        New code should use the ``exponential`` method of a ``default_rng()``
        instance instead; please see the :ref

In [42]:
norm10

array([ 6.79764312,  6.84012133, 10.98205535, 11.82787334,  6.52393271,
       12.70128254,  8.29066393, 14.33980762,  2.66875071,  9.7470593 ])

In [43]:
norm10.shape

(10,)

In [44]:
# we can logically test all elements in an array
# this yields an array of trues and falses
norm10 > 9 

array([False, False,  True,  True, False,  True, False,  True, False,
        True])

In [45]:
# if we assign this to a variable
mask = norm10 > 9

In [46]:
# we can use the variable to index out only true values
norm10[mask]

array([10.98205535, 11.82787334, 12.70128254, 14.33980762,  9.7470593 ])

In [47]:
norm10[mask] = 0

In [48]:
norm10

array([6.79764312, 6.84012133, 0.        , 0.        , 6.52393271,
       0.        , 8.29066393, 0.        , 2.66875071, 0.        ])

In [49]:
# multi dim arrays

samples_list = [[632, 1638, 569, 115], [433, 109, 784, 734]]

samples_array = np.array(samples_list)

In [50]:
samples_array

array([[ 632, 1638,  569,  115],
       [ 433,  109,  784,  734]])

In [51]:
samples_array.shape

(2, 4)

In [52]:
samples_array ** 2

array([[ 399424, 2683044,  323761,   13225],
       [ 187489,   11881,  614656,  538756]])

In [54]:
samples_list[0][0]

632

In [55]:
samples_array[0,0]

632

In [56]:
# create zero filled multidim array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# reshaping arrays
arr = np.arange(8)

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
arr = arr.reshape(2, 4)

In [61]:
arr[1, 2:4]

array([6, 7])

In [62]:
arr[1]

array([4, 5, 6, 7])

In [63]:
# properties and methods associated with arrays

#get my datatype for array
arr.dtype

dtype('int64')

In [64]:
arr.shape

(2, 4)

In [65]:
arr.size

8

In [66]:
arr.ndim

2

In [67]:
arr.nbytes

64

In [68]:
arr.min()

0

In [69]:
arr.max()

7

In [70]:
arr.mean()

3.5

In [71]:
arr.std()

2.29128784747792

In [73]:
arr.mean(axis=0)

array([2., 3., 4., 5.])