# Scipy

In [1]:
import numpy as np

## Linear Algebra

In [2]:
from scipy import linalg

In [ ]:
# Matrix A
# 1  3  5
# 2  5  1
# 2  3  8

# A.A^(-1) = I

# Matrix I
# 1  0  0
# 0  1  0
# 0  0  1

In [3]:
A = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

### Scipy Inverse

In [5]:
Ainv = linalg.inv(A)
Ainv

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

### Check the result

In [15]:
np.rint(linalg.inv(Ainv)).astype(int)

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

## Check the result by multiplication

In [22]:
np.rint(A.dot(Ainv)).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Working with Linear equations

In [23]:
I = np.array([[1, 0, 0],[0, 1, 0], [0, 0, 1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# a . x = b

linalg.solve(A, I)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

## Integration

(0 >> pi/2) | (0 >> 1) y sin(x) dy dx

In [27]:
from scipy.integrate import dblquad

In [48]:
def func(y, x):
  func = y * np.sin(x)
  return func

In [33]:
result = dblquad(func, 0, np.pi/2.0, 0, 1)
result[0]

0.5

In [34]:
#lambda variables: function
# func = lambda y,x : y*np.sin(x)
dblquad(lambda y,x : y*np.sin(x), 0, np.pi/2.0, 0, 1)

(0.5, 5.551115123125783e-15)

(-r >> r) | (-sqrt(r^2 - y^2) >> +sqrt(r^2 - y^2)) 1 dx dy

r = 1

(-1 >> 1) | (-sqrt(1 - y^2) >> +sqrt(1 - y^2)) 1 dx dy


In [35]:
def func(x, y): # order is important
  return 1

def gfun(y):
  gfun = -1*np.sqrt(1 - y*y)
  return gfun

def hfun(y):
  hfun = +1*np.sqrt(1 - y*y)
  return hfun

my_pi = dblquad(func, -1, +1, gfun, hfun)
my_pi
  

(3.1415926535897967, 2.000470900043183e-09)

## Generalising

In [47]:
def func(x, y): # order is important
  return 1

def gfun(y, r):
  gfun = -1*np.sqrt(r*r - y*y)
  return gfun

def hfun(y, r):
  hfun = +1*np.sqrt(r*r - y*y)
  return hfun

r = 1587415
my_pi = dblquad(func, -r, +r, lambda a: gfun(a, r), lambda x: hfun(x, r))
my_pi[0]/(r*r)

3.141592653589798